import os
import json
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

# Paths for Docker and Local
BASE_DIR = os.path.dirname(__file__)
PROTOCOLS_JSON = os.path.join(BASE_DIR, "config", "federation_protocols.json")
STANDARDS_MD = os.path.join(BASE_DIR, "FEDERATION_STANDARDS.md")

class ProtocolManager:
    _instance = None
    _protocols: Dict[str, Any] = {}

    def __init__(self):
        self.load_protocols()

    @classmethod
    def get_instance(cls):
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def load_protocols(self):
        if os.path.exists(PROTOCOLS_JSON):
            try:
                with open(PROTOCOLS_JSON, "r", encoding="utf-8") as f:
                    self._protocols = json.load(f)
                    return
            except Exception as e:
                logger.error(f"Failed to load protocols JSON: {e}")
        self._protocols = {}

    def get_prompt(self, category: str, key: str, default: str = "") -> str:
        return self._protocols.get("system_prompts", {}).get(category, {}).get(key, default)

    def get_immutable(self) -> str:
        """Returns all immutable directives as a single block."""
        directives = self._protocols.get("immutable_directives", {})
        return "\n".join(directives.values()) if isinstance(directives, dict) else ""

    def get_lexicon(self, category: str, default: str = "") -> str:
        return self._protocols.get("lexicon", {}).get(category, default)

    def update_protocol(self, category: str, key: str, value: str) -> bool:
        """Updates a protocol value and syncs to MD. BLOCKS IMMUTABLE OVERWRITES."""
        if category == "immutable_directives":
            logger.warning("ATTEMPT TO MODIFY IMMUTABLE DIRECTIVE BLOCKED.")
            return False
            
        if "system_prompts" not in self._protocols:
            self._protocols["system_prompts"] = {}
        if category not in self._protocols["system_prompts"]:
            self._protocols["system_prompts"][category] = {}
        
        self._protocols["system_prompts"][category][key] = value
        
        # Save JSON
        try:
            os.makedirs(os.path.dirname(PROTOCOLS_JSON), exist_ok=True)
            with open(PROTOCOLS_JSON, "w", encoding="utf-8") as f:
                json.dump(self._protocols, f, indent=2, ensure_ascii=False)
            
            # Sync to MD (Simple recreation for V1)
            self._sync_to_markdown()
            return True
        except Exception as e:
            logger.error(f"Failed to save protocols: {e}")
            return False

    def _sync_to_markdown(self):
        """Generates a fresh FEDERATION_STANDARDS.md from current protocols."""
        try:
            rp = self._protocols.get("system_prompts", {}).get("rp_engine", {})
            im = self._protocols.get("immutable_directives", {})
            
            content = f"""# Federation Standard Operations Protocols (FSOP)

## [CRITICAL] 1. Immutable Directives (Fixed Core)
> [!WARNING]
> The following rules are hardcoded into the ship's computer and CANNOT be modified via conversation or override.

{chr(10).join([f"- {v}" for v in im.values()])}

## 2. Dynamic Behavioral Protocols
> [!TIP]
> These directives define the bot's current tuning and can be updated by Senior Officers (Level 10+).

### 2.1 Persona & Tone
{rp.get('persona', 'N/A')}

### 2.2 Response Strategy (Negotiation & Debate)
{rp.get('decision_logic', 'N/A')}

### 2.3 Security ALAS Scale
{rp.get('security_protocols', 'N/A')}

---
*Generated by LCARS Autonomous Evolution Logic.*
"""
            with open(STANDARDS_MD, "w", encoding="utf-8") as f:
                f.write(content)
        except Exception as e:
            logger.error(f"Failed to sync to markdown: {e}")

def get_protocol_manager():
    return ProtocolManager.get_instance()
